### ISSUE TITLE
Hardcoded information about papers in softconf script

### ISSUE THREAD

**Issue by carolscarton** [rycolab/aclpub2#141] opened 2023-03-10 16:26 UTC
Hi, 

There was some information hardcoded in lines in the script to extract information from SoftConf. Basically, there were hardcoded keys and information that I believe were added to extract "demonstrations", but are not ideal for main conference and others. 

I opened a pull request that should solve the issue.

Carol

**Comment by crux82** [comment] 2023-04-15 15:30
@carolscarton if you confirm that the issue is solved, can you please close this issue?

**Closed** 2023-04-16 10:13 UTC
